#### Environment Set Up

In [2]:
# Install Kaggle API for dataset access
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (1.7.4.5)
Requirement already satisfied: bleach in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (2025.4.26)
Requirement already satisfied: charset-normalizer in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (6.31.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (80.7.1)
Requirement already satisfied: six>=1.10 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: colorama in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [3]:
# Install dotenv to securely manage environment variables
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (1.1.0)

In [4]:
# Install pandas for data handling
!pip install pandas

Requirement already satisfied: pandas in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#### Data Loading and Inspection

In [5]:
# Load environment variables from a .env file
import os
from dotenv import load_dotenv
load_dotenv()

# Set Kaggle API credentials as environment variables
KAGGLE_USERNAME = os.getenv('KAGGLE_USERNAME')
KAGGLE_KEY= os.getenv('KAGGLE_KEY')

In [6]:
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()

In [7]:
# Use Kaggle CLI to download the Retail Orders dataset
!kaggle datasets download -d ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
retail-orders.zip: Skipping, found more recently modified local copy (use --force to force download)

In [8]:
# Import the built-in zipfile module to handle ZIP archives
import zipfile

# Open the zip file and extract its contents into the 'orders' folder
with zipfile.ZipFile('retail-orders.zip', 'r') as zip_ref:
    zip_ref.extractall('orders')

In [9]:
# Import the pandas library for data manipulation
import pandas as pd

# Load the CSV file into a DataFrame and Display the first 30 rows to preview the dataset
retail = pd.read_csv('orders/orders.csv')
retail.head(30)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3
20,21,2022-10-05,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Binders,OFF-BI-10002215,20,20,4,2
21,22,2023-07-16,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Art,OFF-AR-10000246,20,20,7,4
22,23,2023-05-06,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Appliances,OFF-AP-10001492,50,60,7,3
23,24,2023-05-21,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Chairs,FUR-CH-10002774,60,70,2,4
24,25,2023-02-24,Standard Class,Consumer,United States,Orem,Utah,84057,West,Furniture,Tables,FUR-TA-10000577,900,1040,3,5
25,26,2022-06-20,Second Class,Consumer,United States,Los Angeles,California,90049,West,Office Supplies,Binders,OFF-BI-10001634,10,10,2,5
26,27,2022-02-08,Second Class,Consumer,United States,Los Angeles,California,90049,West,Technology,Accessories,TEC-AC-10003027,80,90,3,3
27,28,2023-12-11,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,FUR-BO-10004834,2740,3080,7,3
28,29,2022-08-21,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Office Supplies,Binders,OFF-BI-10000474,10,10,2,5
29,30,2022-08-14,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Furnishings,FUR-FU-10004848,100,120,3,4

In [10]:
# Check the number of rows and columns in the dataset
retail.shape

(9994, 16)

In [11]:
# Count the number of missing values in each column of the dataset
retail.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [12]:
# Display the data type of each column in the retail DataFrame
retail.dtypes

Order Id             int64
Order Date          object
Ship Mode           object
Segment             object
Country             object
City                object
State               object
Postal Code          int64
Region              object
Category            object
Sub Category        object
Product Id          object
cost price           int64
List Price           int64
Quantity             int64
Discount Percent     int64
dtype: object

#### Data Cleaning and Transformation

In [13]:
# Looping through all columns with data type 'object'. 
for col in retail.select_dtypes(include = 'object').columns:
    if col != 'Order Date':
        print(f"Unique values in '{col}': ")
        print(retail[col].unique())
        print('-' * 40)

Unique values in 'Ship Mode':
['Second Class' 'Standard Class' 'Not Available' 'unknown' 'First Class'
 nan 'Same Day']
----------------------------------------
Unique values in 'Segment':
['Consumer' 'Corporate' 'Home Office']
----------------------------------------
Unique values in 'Country':
['United States']
----------------------------------------
Unique values in 'City':
['Henderson' 'Los Angeles' 'Fort Lauderdale' 'Concord' 'Seattle'
 'Fort Worth' 'Madison' 'West Jordan' 'San Francisco' 'Fremont'
 'Philadelphia' 'Orem' 'Houston' 'Richardson' 'Naperville' 'Melbourne'
 'Eagan' 'Westland' 'Dover' 'New Albany' 'New York City' 'Troy' 'Chicago'
 'Gilbert' 'Springfield' 'Jackson' 'Memphis' 'Decatur' 'Durham' 'Columbia'
 'Rochester' 'Minneapolis' 'Portland' 'Saint Paul' 'Aurora' 'Charlotte'
 'Orland Park' 'Urbandale' 'Columbus' 'Bristol' 'Wilmington' 'Bloomington'
 'Phoenix' 'Roseville' 'Independence' 'Pasadena' 'Newark' 'Franklin'
 'Scottsdale' 'San Jose' 'Edmond' 'Carlsbad' 'San Antonio' 'Monroe'
 'Fairfield' 'Grand Prairie' 'Redlands' 'Hamilton' 'Westfield' 'Akron'
 'Denver' 'Dallas' 'Whittier' 'Saginaw' 'Medina' 'Dublin' 'Detroit'
 'Tampa' 'Santa Clara' 'Lakeville' 'San Diego' 'Brentwood' 'Chapel Hill'
 'Morristown' 'Cincinnati' 'Inglewood' 'Tamarac' 'Colorado Springs'
 'Belleville' 'Taylor' 'Lakewood' 'Arlington' 'Arvada' 'Hackensack'
 'Saint Petersburg' 'Long Beach' 'Hesperia' 'Murfreesboro' 'Layton'
 'Austin' 'Lowell' 'Manchester' 'Harlingen' 'Tucson' 'Quincy'
 'Pembroke Pines' 'Des Moines' 'Peoria' 'Las Vegas' 'Warwick' 'Miami'
 'Huntington Beach' 'Richmond' 'Louisville' 'Lawrence' 'Canton'
 'New Rochelle' 'Gastonia' 'Jacksonville' 'Auburn' 'Norman' 'Park Ridge'
 'Amarillo' 'Lindenhurst' 'Huntsville' 'Fayetteville' 'Costa Mesa'
 'Parker' 'Atlanta' 'Gladstone' 'Great Falls' 'Lakeland' 'Montgomery'
 'Mesa' 'Green Bay' 'Anaheim' 'Marysville' 'Salem' 'Laredo' 'Grove City'
 'Dearborn' 'Warner Robins' 'Vallejo' 'Mission Viejo' 'Rochester Hills'
 'Plainfield' 'Sierra Vista' 'Vancouver' 'Cleveland' 'Tyler' 'Burlington'
 'Waynesboro' 'Chester' 'Cary' 'Palm Coast' 'Mount Vernon' 'Hialeah'
 'Oceanside' 'Evanston' 'Trenton' 'Cottage Grove' 'Bossier City'
 'Lancaster' 'Asheville' 'Lake Elsinore' 'Omaha' 'Edmonds' 'Santa Ana'
 'Milwaukee' 'Florence' 'Lorain' 'Linden' 'Salinas' 'New Brunswick'
 'Garland' 'Norwich' 'Alexandria' 'Toledo' 'Farmington' 'Riverside'
 'Torrance' 'Round Rock' 'Boca Raton' 'Virginia Beach' 'Murrieta'
 'Olympia' 'Washington' 'Jefferson City' 'Saint Peters' 'Rockford'
 'Brownsville' 'Yonkers' 'Oakland' 'Clinton' 'Encinitas' 'Roswell'
 'Jonesboro' 'Antioch' 'Homestead' 'La Porte' 'Lansing' 'Cuyahoga Falls'
 'Reno' 'Harrisonburg' 'Escondido' 'Royal Oak' 'Rockville' 'Coral Springs'
 'Buffalo' 'Boynton Beach' 'Gulfport' 'Fresno' 'Greenville' 'Macon'
 'Cedar Rapids' 'Providence' 'Pueblo' 'Deltona' 'Murray' 'Middletown'
 'Freeport' 'Pico Rivera' 'Provo' 'Pleasant Grove' 'Smyrna' 'Parma'
 'Mobile' 'New Bedford' 'Irving' 'Vineland' 'Glendale' 'Niagara Falls'
 'Thomasville' 'Westminster' 'Coppell' 'Pomona' 'North Las Vegas'
 'Allentown' 'Tempe' 'Laguna Niguel' 'Bridgeton' 'Everett' 'Watertown'
 'Appleton' 'Bellevue' 'Allen' 'El Paso' 'Grapevine' 'Carrollton' 'Kent'
 'Lafayette' 'Tigard' 'Skokie' 'Plano' 'Suffolk' 'Indianapolis' 'Bayonne'
 'Greensboro' 'Baltimore' 'Kenosha' 'Olathe' 'Tulsa' 'Redmond' 'Raleigh'
 'Muskogee' 'Meriden' 'Bowling Green' 'South Bend' 'Spokane' 'Keller'
 'Port Orange' 'Medford' 'Charlottesville' 'Missoula' 'Apopka' 'Reading'
 'Broomfield' 'Paterson' 'Oklahoma City' 'Chesapeake' 'Lubbock'
 'Johnson City' 'San Bernardino' 'Leominster' 'Bozeman' 'Perth Amboy'
 'Ontario' 'Rancho Cucamonga' 'Moorhead' 'Mesquite' 'Stockton'
 'Ormond Beach' 'Sunnyvale' 'York' 'College Station' 'Saint Louis'
 'Manteca' 'San Angelo' 'Salt Lake City' 'Knoxville' 'Little Rock'
 'Lincoln Park' 'Marion' 'Littleton' 'Bangor' 'Southaven' 'New Castle'
 'Midland' 'Sioux Falls' 'Fort Collins' 'Clarksville' 'Sacramento'
 'Thousand Oaks' 'Malden' 'Holyoke' 'Albuquerque' 'Sparks' 'Coachella'
 'Elmhurst' 'Passaic' 'North Charleston' 'Newport News' 'Jamestown'
 'Mishawaka' 'La Quinta' 'Tallahassee' 'Nashville' 'Bellingham'
 'Woodstock' 'Haltom City' 'Wheeling' 'Summerville' 'Hot Springs'
 'Englewood' 'Las Cruces' 'Hoover' 'Frisco' 'Vacaville' 'Waukesha'
 'Bakersfield' 'Pompano Beach' 'Corpus Christi' 'Redondo Beach' 'Orlando'
 'Orange' 'Lake Charles' 'Highland Park' 'Hempstead' 'Noblesville'
 'Apple Valley' 'Mount Pleasant' 'Sterling Heights' 'Eau Claire' 'Pharr'
 'Billings' 'Gresham' 'Chattanooga' 'Meridian' 'Bolingbrook' 'Maple Grove'
 'Woodland' 'Missouri City' 'Pearland' 'San Mateo' 'Grand Rapids'
 'Visalia' 'Overland Park' 'Temecula' 'Yucaipa' 'Revere' 'Conroe'
 'Tinley Park' 'Dubuque' 'Dearborn Heights' 'Santa Fe' 'Hickory'
 'Carol Stream' 'Saint Cloud' 'North Miami' 'Plantation'
 'Port Saint Lucie' 'Rock Hill' 'Odessa' 'West Allis' 'Chula Vista'
 'Manhattan' 'Altoona' 'Thornton' 'Champaign' 'Texarkana' 'Edinburg'
 'Baytown' 'Greenwood' 'Woonsocket' 'Superior' 'Bedford' 'Covington'
 'Broken Arrow' 'Miramar' 'Hollywood' 'Deer Park' 'Wichita' 'Mcallen'
 'Iowa City' 'Boise' 'Cranston' 'Port Arthur' 'Citrus Heights'
 'The Colony' 'Daytona Beach' 'Bullhead City' 'Portage' 'Fargo' 'Elkhart'
 'San Gabriel' 'Margate' 'Sandy Springs' 'Mentor' 'Lawton' 'Hampton'
 'Rome' 'La Crosse' 'Lewiston' 'Hattiesburg' 'Danville' 'Logan'
 'Waterbury' 'Athens' 'Avondale' 'Marietta' 'Yuma' 'Wausau' 'Pasco'
 'Oak Park' 'Pensacola' 'League City' 'Gaithersburg' 'Lehi' 'Tuscaloosa'
 'Moreno Valley' 'Georgetown' 'Loveland' 'Chandler' 'Helena' 'Kirkwood'
 'Waco' 'Frankfort' 'Bethlehem' 'Grand Island' 'Woodbury' 'Rogers'
 'Clovis' 'Jupiter' 'Santa Barbara' 'Cedar Hill' 'Norfolk' 'Draper'
 'Ann Arbor' 'La Mesa' 'Pocatello' 'Holland' 'Milford' 'Buffalo Grove'
 'Lake Forest' 'Redding' 'Chico' 'Utica' 'Conway' 'Cheyenne' 'Owensboro'
 'Caldwell' 'Kenner' 'Nashua' 'Bartlett' 'Redwood City' 'Lebanon'
 'Santa Maria' 'Des Plaines' 'Longview' 'Hendersonville' 'Waterloo'
 'Cambridge' 'Palatine' 'Beverly' 'Eugene' 'Oxnard' 'Renton' 'Glenview'
 'Delray Beach' 'Commerce City' 'Texas City' 'Wilson' 'Rio Rancho'
 'Goldsboro' 'Montebello' 'El Cajon' 'Beaumont' 'West Palm Beach'
 'Abilene' 'Normal' 'Saint Charles' 'Camarillo' 'Hillsboro' 'Burbank'
 'Modesto' 'Garden City' 'Atlantic City' 'Longmont' 'Davis' 'Morgan Hill'
 'Clifton' 'Sheboygan' 'East Point' 'Rapid City' 'Andover' 'Kissimmee'
 'Shelton' 'Danbury' 'Sanford' 'San Marcos' 'Greeley' 'Mansfield' 'Elyria'
 'Twin Falls' 'Coral Gables' 'Romeoville' 'Marlborough' 'Laurel' 'Bryan'
 'Pine Bluff' 'Aberdeen' 'Hagerstown' 'East Orange' 'Arlington Heights'
 'Oswego' 'Coon Rapids' 'San Clemente' 'San Luis Obispo' 'Springdale'
 'Lodi' 'Mason']
----------------------------------------
Unique values in 'State':
['Kentucky' 'California' 'Florida' 'North Carolina' 'Washington' 'Texas'
 'Wisconsin' 'Utah' 'Nebraska' 'Pennsylvania' 'Illinois' 'Minnesota'
 'Michigan' 'Delaware' 'Indiana' 'New York' 'Arizona' 'Virginia'
 'Tennessee' 'Alabama' 'South Carolina' 'Oregon' 'Colorado' 'Iowa' 'Ohio'
 'Missouri' 'Oklahoma' 'New Mexico' 'Louisiana' 'Connecticut' 'New Jersey'
 'Massachusetts' 'Georgia' 'Nevada' 'Rhode Island' 'Mississippi'
 'Arkansas' 'Montana' 'New Hampshire' 'Maryland' 'District of Columbia'
 'Kansas' 'Vermont' 'Maine' 'South Dakota' 'Idaho' 'North Dakota'
 'Wyoming' 'West Virginia']
----------------------------------------
Unique values in 'Region':
['South' 'West' 'Central' 'East']
----------------------------------------
Unique values in 'Category':
['Furniture' 'Office Supplies' 'Technology']
----------------------------------------
Unique values in 'Sub Category':
['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']
----------------------------------------
Unique values in 'Product Id':
['FUR-BO-10001798' 'FUR-CH-10000454' 'OFF-LA-10000240' ...
 'OFF-AP-10003099' 'TEC-PH-10002645' 'OFF-ST-10001627']
----------------------------------------

In [14]:
# Replace Invalids:Replace the entries 'Not Available' and 'unknown' in the Ship Mode column with NaN.
retail['Ship Mode'] = retail['Ship Mode'].replace(['Not Available', 'unknown'], pd.NA)
print(retail['Ship Mode'])

0         Second Class
1         Second Class
2         Second Class
3       Standard Class
4       Standard Class
             ...
9989      Second Class
9990    Standard Class
9991    Standard Class
9992    Standard Class
9993      Second Class
Name: Ship Mode, Length: 9994, dtype: object

In [15]:
# Rename Columns:Rename all DataFrame columns by lowercasing and replacing spaces with underscores.
# lowercasing
retail.columns = retail.columns.str.lower()
retail.columns

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [16]:
# replacing spaces with underscores
retail.columns = retail.columns.str.replace(' ', '_')
retail.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [17]:
# Create Derived Columns
# Compute a discount column as list_price * discount_percent / 100
retail['discount'] = retail['list_price'] * retail['discount_percent']/100
retail

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2

In [18]:
#Compute a selling_price column as list_price - discount.
retail['selling_price'] = retail['list_price'] - retail['discount']
retail

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,selling_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8

In [19]:
# Compute a profit column as selling_price - cost_price.
retail['profit'] = retail['selling_price'] - retail['cost_price']
retail

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,selling_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [20]:
# Drop Unneeded Columns: Remove cost_price, list_price, and discount_percent from the DataFrame.
retail = retail.drop(columns=['cost_price', 'list_price', 'discount_percent'])

In [21]:
print(retail.columns)

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'selling_price', 'profit'],
      dtype='object')

In [22]:
# Datetime Conversion: Convert the order_date column to pandas datetime with ISO8601 format.
retail['order_date'] = pd.to_datetime(retail['order_date'])
retail

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,selling_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

#### Database Creation and Schema Definition

In [23]:
# Create Database (SQL Script):
!pip install sqlalchemy psycopg2

Requirement already satisfied: sqlalchemy in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (2.0.41)
Requirement already satisfied: psycopg2 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (2.9.10)
Requirement already satisfied: greenlet>=1 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from sqlalchemy) (3.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\administrator\desktop\lux\projects\assignment\retail_orders_analysis\.venv\lib\site-packages (from sqlalchemy) (4.13.2)

In [24]:

import os
from dotenv import load_dotenv
load_dotenv

db = os.getenv('PG_NAME')
user = os.getenv('PG_USER')
password = os.getenv('PG_PASSWORD')
host = os.getenv('PG_HOST')
port = os.getenv('PG_PORT')

In [25]:
import urllib.parse # <-- This is important for encoding special characters
password_encoded = urllib.parse.quote_plus(str(password)) #Encoding my password to safely use it in the connection URL

In [26]:
# Building my connection string with encoded password (# dialect+driver://username:password@host:port/database)
DATABASE_URL =f"postgresql+psycopg2://{user}:{password_encoded}@{host}:{port}/{db}"

In [27]:
from sqlalchemy import create_engine  # Import and Create the Engine
engine = create_engine(DATABASE_URL, echo=True)
 # You can add parameters like echo=True in create_engine() to see SQL statements printed out:

In [28]:
# loading the dataset to our database
retail.to_sql('orders', engine, if_exists='replace', index=False, schema='retail_orders')

# 'orders' -> table name

# engine -> your SQLAlchemy connection

# if_exists='replace' -> will drop and recreate the table

# index=False -> don’t insert the DataFrame’s index as a column

# schema='retail_orders' -> write the table inside a custom schema, not the default public

2025-05-25 21:33:15,057 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-05-25 21:33:15,061 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-25 21:33:15,066 INFO sqlalchemy.engine.Engine select current_schema()
2025-05-25 21:33:15,075 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-25 21:33:15,079 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-05-25 21:33:15,081 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-25 21:33:15,084 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-25 21:33:15,112 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
2025-05-25 21:33:15,114 INFO sqlalchemy.engine.Engine [generated in 0.00218s] {'table_name': 'orders', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'retail_orders'}
2025-05-25 21:33:15,132 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
2025-05-25 21:33:15,135 INFO sqlalchemy.engine.Engine [cached since 0.02264s ago] {'table_name': 'orders', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'retail_orders'}
2025-05-25 21:33:15,144 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
2025-05-25 21:33:15,146 INFO sqlalchemy.engine.Engine [generated in 0.00206s] {'param_1': 'r', 'param_2': 'p', 'relpersistence_1': 't', 'nspname_1': 'retail_orders'}
2025-05-25 21:33:15,157 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
2025-05-25 21:33:15,159 INFO sqlalchemy.engine.Engine [generated in 0.00196s] {'param_1': 'v', 'relpersistence_1': 't', 'nspname_1': 'retail_orders'}
2025-05-25 21:33:15,164 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
2025-05-25 21:33:15,167 INFO sqlalchemy.engine.Engine [cached since 0.009712s ago] {'param_1': 'm', 'relpersistence_1': 't', 'nspname_1': 'retail_orders'}
2025-05-25 21:33:15,198 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_attribute.attname AS name, pg_catalog.format_type(pg_catalog.pg_attribute.atttypid, pg_catalog.pg_attribute.atttypmod) AS format_type, (SELECT pg_catalog.pg_get_expr(pg_catalog.pg_attrdef.adbin, pg_catalog.pg_attrdef.adrelid) AS pg_get_expr_1
FROM pg_catalog.pg_attrdef
WHERE pg_catalog.pg_attrdef.adrelid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attrdef.adnum = pg_catalog.pg_attribute.attnum AND pg_catalog.pg_attribute.atthasdef) AS "default", pg_catalog.pg_attribute.attnotnull AS not_null, pg_catalog.pg_class.relname AS table_name, pg_catalog.pg_description.description AS comment, pg_catalog.pg_attribute.attgenerated AS generated, (SELECT json_build_object(%(json_build_object_2)s, pg_catalog.pg_attribute.attidentity = %(attidentity_1)s, %(json_build_object_3)s, pg_catalog.pg_sequence.seqstart, %(json_build_object_4)s, pg_catalog.pg_sequence.seqincrement, %(json_build_object_5)s, pg_catalog.pg_sequence.seqmin, %(json_build_object_6)s, pg_catalog.pg_sequence.seqmax, %(json_build_object_7)s, pg_catalog.pg_sequence.seqcache, %(json_build_object_8)s, pg_catalog.pg_sequence.seqcycle) AS json_build_object_1
FROM pg_catalog.pg_sequence
WHERE pg_catalog.pg_attribute.attidentity != %(attidentity_2)s AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog.pg_get_serial_sequence(CAST(CAST(pg_catalog.pg_attribute.attrelid AS REGCLASS) AS TEXT), pg_catalog.pg_attribute.attname) AS REGCLASS) AS OID)) AS identity_options
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_class.oid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attribute.attnum > %(attnum_1)s AND NOT pg_catalog.pg_attribute.attisdropped LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_description.objsubid = pg_catalog.pg_attribute.attnum JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_attribute.attnum
2025-05-25 21:33:15,202 INFO sqlalchemy.engine.Engine [generated in 0.00416s] {'json_build_object_2': 'always', 'attidentity_1': 'a', 'json_build_object_3': 'start', 'json_build_object_4': 'increment', 'json_build_object_5': 'minvalue', 'json_build_object_6': 'maxvalue', 'json_build_object_7': 'cache', 'json_build_object_8': 'cycle', 'attidentity_2': '', 'attnum_1': 0, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'retail_orders', 'filter_names_1': 'orders'}
2025-05-25 21:33:15,259 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname AS name, pg_catalog.format_type(pg_catalog.pg_type.typbasetype, pg_catalog.pg_type.typtypmod) AS attype, NOT pg_catalog.pg_type.typnotnull AS nullable, pg_catalog.pg_type.typdefault AS "default", pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, domain_constraints.condefs, domain_constraints.connames, pg_catalog.pg_collation.collname
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN pg_catalog.pg_collation ON pg_catalog.pg_type.typcollation = pg_catalog.pg_collation.oid LEFT OUTER JOIN (SELECT pg_catalog.pg_constraint.contypid AS contypid, array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s)) AS condefs, array_agg(CAST(pg_catalog.pg_constraint.conname AS TEXT)) AS connames
FROM pg_catalog.pg_constraint
WHERE pg_catalog.pg_constraint.contypid != %(contypid_1)s GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid
WHERE pg_catalog.pg_type.typtype = %(typtype_1)s ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
2025-05-25 21:33:15,260 INFO sqlalchemy.engine.Engine [generated in 0.00197s] {'pg_get_constraintdef_1': True, 'contypid_1': 0, 'typtype_1': 'd'}
2025-05-25 21:33:15,300 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname AS name, pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, lbl_agg.labels AS labels
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN (SELECT pg_catalog.pg_enum.enumtypid AS enumtypid, array_agg(CAST(pg_catalog.pg_enum.enumlabel AS TEXT) ORDER BY pg_catalog.pg_enum.enumsortorder) AS labels
FROM pg_catalog.pg_enum GROUP BY pg_catalog.pg_enum.enumtypid) AS lbl_agg ON pg_catalog.pg_type.oid = lbl_agg.enumtypid
WHERE pg_catalog.pg_type.typtype = %(typtype_1)s ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
2025-05-25 21:33:15,302 INFO sqlalchemy.engine.Engine [generated in 0.00227s] {'typtype_1': 'e'}
2025-05-25 21:33:15,324 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.oid, pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s)
2025-05-25 21:33:15,327 INFO sqlalchemy.engine.Engine [generated in 0.00318s] {'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'retail_orders', 'filter_names_1': 'orders'}
2025-05-25 21:33:15,345 INFO sqlalchemy.engine.Engine SELECT attr.conrelid, array_agg(CAST(attr.attname AS TEXT) ORDER BY attr.ord) AS cols, attr.conname, min(attr.description) AS description, min(attr.indnkeyatts) AS indnkeyatts, bool_and(attr.indnullsnotdistinct) AS indnullsnotdistinct
FROM (SELECT con.conrelid AS conrelid, con.conname AS conname, con.description AS description, con.ord AS ord, con.indnkeyatts AS indnkeyatts, con.indnullsnotdistinct AS indnullsnotdistinct, pg_catalog.pg_attribute.attname AS attname
FROM pg_catalog.pg_attribute JOIN (SELECT pg_catalog.pg_constraint.conrelid AS conrelid, pg_catalog.pg_constraint.conname AS conname, unnest(pg_catalog.pg_index.indkey) AS attnum, generate_subscripts(pg_catalog.pg_index.indkey, %(generate_subscripts_1)s) AS ord, pg_catalog.pg_index.indnkeyatts AS indnkeyatts, pg_catalog.pg_index.indnullsnotdistinct AS indnullsnotdistinct, pg_catalog.pg_description.description AS description
FROM pg_catalog.pg_constraint JOIN pg_catalog.pg_index ON pg_catalog.pg_constraint.conindid = pg_catalog.pg_index.indexrelid LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid
WHERE pg_catalog.pg_constraint.contype = %(contype)s AND pg_catalog.pg_constraint.conrelid IN (%(oids_1)s)) AS con ON pg_catalog.pg_attribute.attnum = con.attnum AND pg_catalog.pg_attribute.attrelid = con.conrelid
WHERE con.conrelid IN (%(oids_1)s)) AS attr GROUP BY attr.conrelid, attr.conname ORDER BY attr.conrelid, attr.conname
2025-05-25 21:33:15,347 INFO sqlalchemy.engine.Engine [generated in 0.00250s] {'generate_subscripts_1': 1, 'contype': 'p', 'oids_1': 24590}
2025-05-25 21:33:15,376 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname, CASE WHEN (pg_catalog.pg_constraint.oid IS NOT NULL) THEN pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s) END AS anon_1, nsp_ref.nspname, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_class.oid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_constraint.contype = %(contype_1)s LEFT OUTER JOIN pg_catalog.pg_class AS cls_ref ON cls_ref.oid = pg_catalog.pg_constraint.confrelid LEFT OUTER JOIN pg_catalog.pg_namespace AS nsp_ref ON cls_ref.relnamespace = nsp_ref.oid LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname
2025-05-25 21:33:15,381 INFO sqlalchemy.engine.Engine [generated in 0.00475s] {'pg_get_constraintdef_1': True, 'contype_1': 'f', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'retail_orders', 'filter_names_1': 'orders'}
2025-05-25 21:33:15,414 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_index.indrelid, pg_catalog.pg_class.relname, pg_catalog.pg_index.indisunique, pg_catalog.pg_constraint.conrelid IS NOT NULL AS has_constraint, pg_catalog.pg_index.indoption, pg_catalog.pg_class.reloptions, pg_catalog.pg_am.amname, CASE WHEN (pg_catalog.pg_index.indpred IS NOT NULL) THEN pg_catalog.pg_get_expr(pg_catalog.pg_index.indpred, pg_catalog.pg_index.indrelid) END AS filter_definition, pg_catalog.pg_index.indnkeyatts, pg_catalog.pg_index.indnullsnotdistinct, idx_cols.elements, idx_cols.elements_is_expr
FROM pg_catalog.pg_index JOIN pg_catalog.pg_class ON pg_catalog.pg_index.indexrelid = pg_catalog.pg_class.oid JOIN pg_catalog.pg_am ON pg_catalog.pg_class.relam = pg_catalog.pg_am.oid LEFT OUTER JOIN (SELECT idx_attr.indexrelid AS indexrelid, min(idx_attr.indrelid) AS min_1, array_agg(idx_attr.element ORDER BY idx_attr.ord) AS elements, array_agg(idx_attr.is_expr ORDER BY idx_attr.ord) AS elements_is_expr
FROM (SELECT idx.indexrelid AS indexrelid, idx.indrelid AS indrelid, idx.ord AS ord, CASE WHEN (idx.attnum = %(attnum_1)s) THEN pg_catalog.pg_get_indexdef(idx.indexrelid, idx.ord + %(ord_1)s, %(pg_get_indexdef_1)s) ELSE CAST(pg_catalog.pg_attribute.attname AS TEXT) END AS element, idx.attnum = %(attnum_2)s AS is_expr
FROM (SELECT pg_catalog.pg_index.indexrelid AS indexrelid, pg_catalog.pg_index.indrelid AS indrelid, unnest(pg_catalog.pg_index.indkey) AS attnum, generate_subscripts(pg_catalog.pg_index.indkey, %(generate_subscripts_1)s) AS ord
FROM pg_catalog.pg_index
WHERE NOT pg_catalog.pg_index.indisprimary AND pg_catalog.pg_index.indrelid IN (%(oids_1)s)) AS idx LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_attribute.attnum = idx.attnum AND pg_catalog.pg_attribute.attrelid = idx.indrelid
WHERE idx.indrelid IN (%(oids_1)s)) AS idx_attr GROUP BY idx_attr.indexrelid) AS idx_cols ON pg_catalog.pg_index.indexrelid = idx_cols.indexrelid LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_index.indrelid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_index.indexrelid = pg_catalog.pg_constraint.conindid AND pg_catalog.pg_constraint.contype = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s])
WHERE pg_catalog.pg_index.indrelid IN (%(oids_1)s) AND NOT pg_catalog.pg_index.indisprimary ORDER BY pg_catalog.pg_index.indrelid, pg_catalog.pg_class.relname
2025-05-25 21:33:15,417 INFO sqlalchemy.engine.Engine [generated in 0.00316s] {'attnum_1': 0, 'ord_1': 1, 'pg_get_indexdef_1': True, 'attnum_2': 0, 'generate_subscripts_1': 1, 'param_1': 'p', 'param_2': 'u', 'param_3': 'x', 'oids_1': 24590}
2025-05-25 21:33:15,432 INFO sqlalchemy.engine.Engine SELECT attr.conrelid, array_agg(CAST(attr.attname AS TEXT) ORDER BY attr.ord) AS cols, attr.conname, min(attr.description) AS description, min(attr.indnkeyatts) AS indnkeyatts, bool_and(attr.indnullsnotdistinct) AS indnullsnotdistinct
FROM (SELECT con.conrelid AS conrelid, con.conname AS conname, con.description AS description, con.ord AS ord, con.indnkeyatts AS indnkeyatts, con.indnullsnotdistinct AS indnullsnotdistinct, pg_catalog.pg_attribute.attname AS attname
FROM pg_catalog.pg_attribute JOIN (SELECT pg_catalog.pg_constraint.conrelid AS conrelid, pg_catalog.pg_constraint.conname AS conname, unnest(pg_catalog.pg_index.indkey) AS attnum, generate_subscripts(pg_catalog.pg_index.indkey, %(generate_subscripts_1)s) AS ord, pg_catalog.pg_index.indnkeyatts AS indnkeyatts, pg_catalog.pg_index.indnullsnotdistinct AS indnullsnotdistinct, pg_catalog.pg_description.description AS description
FROM pg_catalog.pg_constraint JOIN pg_catalog.pg_index ON pg_catalog.pg_constraint.conindid = pg_catalog.pg_index.indexrelid LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid
WHERE pg_catalog.pg_constraint.contype = %(contype)s AND pg_catalog.pg_constraint.conrelid IN (%(oids_1)s)) AS con ON pg_catalog.pg_attribute.attnum = con.attnum AND pg_catalog.pg_attribute.attrelid = con.conrelid
WHERE con.conrelid IN (%(oids_1)s)) AS attr GROUP BY attr.conrelid, attr.conname ORDER BY attr.conrelid, attr.conname
2025-05-25 21:33:15,434 INFO sqlalchemy.engine.Engine [cached since 0.08904s ago] {'generate_subscripts_1': 1, 'contype': 'u', 'oids_1': 24590}
2025-05-25 21:33:15,443 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_class.oid = pg_catalog.pg_description.objoid AND pg_catalog.pg_description.objsubid = %(objsubid_1)s AND pg_catalog.pg_description.classoid = CAST(%(param_1)s AS REGCLASS) JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s, %(param_6)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s)
2025-05-25 21:33:15,444 INFO sqlalchemy.engine.Engine [generated in 0.00173s] {'objsubid_1': 0, 'param_1': 'pg_catalog.pg_class', 'param_2': 'r', 'param_3': 'p', 'param_4': 'f', 'param_5': 'v', 'param_6': 'm', 'nspname_1': 'retail_orders', 'filter_names_1': 'orders'}
2025-05-25 21:33:15,454 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname, CASE WHEN (pg_catalog.pg_constraint.oid IS NOT NULL) THEN pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s) END AS anon_1, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_class.oid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_constraint.contype = %(contype_1)s LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname
2025-05-25 21:33:15,457 INFO sqlalchemy.engine.Engine [generated in 0.00320s] {'pg_get_constraintdef_1': True, 'contype_1': 'c', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'retail_orders', 'filter_names_1': 'orders'}
2025-05-25 21:33:15,466 INFO sqlalchemy.engine.Engine
DROP TABLE retail_orders.orders
2025-05-25 21:33:15,469 INFO sqlalchemy.engine.Engine [no key 0.00266s] {}
2025-05-25 21:33:15,498 INFO sqlalchemy.engine.Engine
CREATE TABLE retail_orders.orders (
	order_id BIGINT,
	order_date TIMESTAMP WITHOUT TIME ZONE,
	ship_mode TEXT,
	segment TEXT,
	country TEXT,
	city TEXT,
	state TEXT,
	postal_code BIGINT,
	region TEXT,
	category TEXT,
	sub_category TEXT,
	product_id TEXT,
	quantity BIGINT,
	discount FLOAT(53),
	selling_price FLOAT(53),
	profit FLOAT(53)
)


2025-05-25 21:33:15,501 INFO sqlalchemy.engine.Engine [no key 0.00330s] {}
2025-05-25 21:33:17,431 INFO sqlalchemy.engine.Engine INSERT INTO retail_orders.orders (order_id, order_date, ship_mode, segment, country, city, state, postal_code, region, category, sub_category, product_id, quantity, discount, selling_price, profit) VALUES (%(order_id__0)s, %(order_date__0)s, %(ship_m ... 308093 characters truncated ...  %(product_id__999)s, %(quantity__999)s, %(discount__999)s, %(selling_price__999)s, %(profit__999)s)

994

In [29]:
from sqlalchemy import text

# Step 1: Write the SQL query
query = text("SELECT * FROM retail_orders.orders")

# Step 2: Execute the query
with engine.connect() as conn:
    result = conn.execute(query)

    # Step 3: Fetch all results
    rows = result.fetchall()

# Step 4: Print or work with the data
for row in rows:
    print(row)

2025-05-25 21:33:22,625 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-25 21:33:22,628 INFO sqlalchemy.engine.Engine SELECT * FROM retail_orders.orders
2025-05-25 21:33:22,632 INFO sqlalchemy.engine.Engine [generated in 0.00624s] {}
2025-05-25 21:33:22,916 INFO sqlalchemy.engine.Engine ROLLBACK
(1, datetime.datetime(2023, 3, 1, 0, 0), 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', 42420, 'South', 'Furniture', 'Bookcases', 'FUR-BO-10001798', 2, 5.2, 254.8, 14.800000000000011)
(2, datetime.datetime(2023, 8, 15, 0, 0), 'Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', 42420, 'South', 'Furniture', 'Chairs', 'FUR-CH-10000454', 3, 21.9, 708.1, 108.10000000000002)
(3, datetime.datetime(2023, 1, 10, 0, 0), 'Second Class', 'Corporate', 'United States', 'Los Angeles', 'California', 90036, 'West', 'Office Supplies', 'Labels', 'OFF-LA-10000240', 2, 0.5, 9.5, -0.5)
(4, datetime.datetime(2022, 6, 18, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', 33311, 'South', 'Furniture', 'Tables', 'FUR-TA-10000577', 5, 19.2, 940.8, 160.79999999999995)
(5, datetime.datetime(2022, 7, 13, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', 33311, 'South', 'Office Supplies', 'Storage', 'OFF-ST-10000760', 2, 1.0, 19.0, -1.0)
(6, datetime.datetime(2022, 3, 13, 0, 0), None, 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Furniture', 'Furnishings', 'FUR-FU-10001487', 7, 1.5, 48.5, -1.5)
(7, datetime.datetime(2022, 12, 28, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Office Supplies', 'Art', 'OFF-AR-10002833', 4, 0.3, 9.7, -0.3000000000000007)
(8, datetime.datetime(2022, 1, 25, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Technology', 'Phones', 'TEC-PH-10002275', 6, 45.5, 864.5, 4.5)
(9, datetime.datetime(2023, 3, 23, 0, 0), None, 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Office Supplies', 'Binders', 'OFF-BI-10003910', 3, 0.4, 19.6, -0.3999999999999986)
(10, datetime.datetime(2023, 5, 16, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Office Supplies', 'Appliances', 'OFF-AP-10002892', 5, 3.3, 106.7, 16.700000000000003)
(11, datetime.datetime(2023, 3, 31, 0, 0), None, 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Furniture', 'Tables', 'FUR-TA-10001539', 9, 51.3, 1658.7, 188.70000000000005)
(12, datetime.datetime(2023, 12, 25, 0, 0), None, 'Consumer', 'United States', 'Los Angeles', 'California', 90032, 'West', 'Technology', 'Phones', 'TEC-PH-10002033', 4, 27.3, 882.7, 132.70000000000005)
(13, datetime.datetime(2022, 2, 11, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Concord', 'North Carolina', 28027, 'South', 'Office Supplies', 'Paper', 'OFF-PA-10002365', 3, 0.6, 19.4, -0.6000000000000014)
(14, datetime.datetime(2023, 7, 18, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Seattle', 'Washington', 98103, 'West', 'Office Supplies', 'Binders', 'OFF-BI-10003656', 3, 8.2, 401.8, 41.80000000000001)
(15, datetime.datetime(2023, 11, 9, 0, 0), None, 'Home Office', 'United States', 'Fort Worth', 'Texas', 76106, 'Central', 'Office Supplies', 'Appliances', 'OFF-AP-10002311', 5, 3.5, 66.5, 6.5)
(16, datetime.datetime(2022, 6, 18, 0, 0), 'Standard Class', 'Home Office', 'United States', 'Fort Worth', 'Texas', 76106, 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10000756', 3, 0.0, 0.0, 0.0)
(17, datetime.datetime(2022, 2, 4, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Madison', 'Wisconsin', 53711, 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10004186', 6, 20.1, 649.9, 39.89999999999998)
(18, datetime.datetime(2023, 8, 4, 0, 0), 'Second Class', 'Consumer', 'United States', 'West Jordan', 'Utah', 84084, 'West', 'Office Supplies', 'Storage', 'OFF-ST-10000107', 2, 2.4, 57.6, -2.3999999999999986)
(19, datetime.datetime(2022, 1, 23, 0, 0), 'Second Class', 'Consumer', 'United States', 'San Francisco', 'California', 94109, 'West', 'Office Supplies', 'Art', 'OFF-AR-10003056', 2, 0.4, 9.6, -0.40000000000000036)
(20, datetime.datetime(2022, 1, 11, 0, 0), 'Second Class', 'Consumer', 'United States', 'San Francisco', 'California', 94109, 'West', 'Technology', 'Phones', 'TEC-PH-10001949', 3, 6.3, 203.7, 33.69999999999999)
(21, datetime.datetime(2022, 10, 5, 0, 0), 'Second Class', 'Consumer', 'United States', 'San Francisco', 'California', 94109, 'West', 'Office Supplies', 'Binders', 'OFF-BI-10002215', 4, 0.4, 19.6, -0.3999999999999986)
(22, datetime.datetime(2023, 7, 16, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Fremont', 'Nebraska', 68025, 'Central', 'Office Supplies', 'Art', 'OFF-AR-10000246', 7, 0.8, 19.2, -0.8000000000000007)
(23, datetime.datetime(2023, 5, 6, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Fremont', 'Nebraska', 68025, 'Central', 'Office Supplies', 'Appliances', 'OFF-AP-10001492', 7, 1.8, 58.2, 8.200000000000003)
(24, datetime.datetime(2023, 5, 21, 0, 0), 'Second Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Furniture', 'Chairs', 'FUR-CH-10002774', 2, 2.8, 67.2, 7.200000000000003)
(25, datetime.datetime(2023, 2, 24, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Orem', 'Utah', 84057, 'West', 'Furniture', 'Tables', 'FUR-TA-10000577', 3, 52.0, 988.0, 88.0)
(26, datetime.datetime(2022, 6, 20, 0, 0), 'Second Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90049, 'West', 'Office Supplies', 'Binders', 'OFF-BI-10001634', 2, 0.5, 9.5, -0.5)
(27, datetime.datetime(2022, 2, 8, 0, 0), 'Second Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90049, 'West', 'Technology', 'Accessories', 'TEC-AC-10003027', 3, 2.7, 87.3, 7.299999999999997)
(28, datetime.datetime(2023, 12, 11, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Furniture', 'Bookcases', 'FUR-BO-10004834', 7, 92.4, 2987.6, 247.5999999999999)
(29, datetime.datetime(2022, 8, 21, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Office Supplies', 'Binders', 'OFF-BI-10000474', 2, 0.5, 9.5, -0.5)
(30, datetime.datetime(2022, 8, 14, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Furniture', 'Furnishings', 'FUR-FU-10004848', 3, 4.8, 115.2, 15.200000000000003)
(31, datetime.datetime(2022, 11, 20, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Office Supplies', 'Envelopes', 'OFF-EN-10001509', 2, 0.0, 0.0, 0.0)
(32, datetime.datetime(2023, 1, 19, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Office Supplies', 'Art', 'OFF-AR-10004042', 6, 3.6, 86.4, 16.400000000000006)
(33, datetime.datetime(2023, 1, 30, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Office Supplies', 'Binders', 'OFF-BI-10001525', 6, 0.5, 9.5, -0.5)
(34, datetime.datetime(2022, 6, 3, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Philadelphia', 'Pennsylvania', 19140, 'East', 'Office Supplies', 'Art', 'OFF-AR-10001683', 2, 0.8, 19.2, -0.8000000000000007)
(35, datetime.datetime(2022, 9, 28, 0, 0), 'Second Class', 'Home Office', 'United States', 'Houston', 'Texas', 77095, 'Central', 'Office Supplies', 'Paper', 'OFF-PA-10000249', 3, 0.9, 29.1, -0.8999999999999986)
(36, datetime.datetime(2022, 10, 30, 0, 0), 'First Class', 'Corporate', 'United States', 'Richardson', 'Texas', 75080, 'Central', 'Technology', 'Phones', 'TEC-PH-10004977', 7, 55.0, 1045.0, 25.0)
(37, datetime.datetime(2023, 7, 27, 0, 0), 'First Class', 'Corporate', 'United States', 'Richardson', 'Texas', 75080, 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10003664', 5, 7.6, 182.4, 2.4000000000000057)
(38, datetime.datetime(2023, 3, 7, 0, 0), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', 77041, 'Central', 'Office Supplies', 'Envelopes', 'OFF-EN-10002986', 9, 2.2, 107.8, 17.799999999999997)
(39, datetime.datetime(2023, 8, 18, 0, 0), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', 77041, 'Central', 'Furniture', 'Bookcases', 'FUR-BO-10002545', 3, 10.6, 519.4, 59.39999999999998)
(40, datetime.datetime(2022, 1, 20, 0, 0), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', 77041, 'Central', 'Furniture', 'Chairs', 'FUR-CH-10004218', 3, 4.2, 205.8, 5.800000000000011)
(41, datetime.datetime(2023, 6, 29, 0, 0), 'Standard Class', 'Home Office', 'United States', 'Houston', 'Texas', 77041, 'Central', 'Technology', 'Phones', 'TEC-PH-10000486', 4, 18.5, 351.5, 1.5)
(42, datetime.datetime(2022, 6, 28, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Naperville', 'Illinois', 60540, 'Central', 'Technology', 'Phones', 'TEC-PH-10004093', 4, 4.5, 145.5, 5.5)
(43, datetime.datetime(2023, 2, 9, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Los Angeles', 'California', 90049, 'West', 'Office Supplies', 'Storage', 'OFF-ST-10003479', 2, 4.0, 76.0, 6.0)
(44, datetime.datetime(2023, 9, 18, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Melbourne', 'Florida', 32935, 'South', 'Office Supplies', 'Storage', 'OFF-ST-10003282', 2, 4.0, 96.0, 6.0)
(45, datetime.datetime(2022, 11, 11, 0, 0), 'First Class', 'Corporate', 'United States', 'Eagan', 'Minnesota', 55122, 'Central', 'Technology', 'Accessories', 'TEC-AC-10000171', 2, 1.0, 49.0, 9.0)
(46, datetime.datetime(2022, 5, 27, 0, 0), 'First Class', 'Corporate', 'United States', 'Eagan', 'Minnesota', 55122, 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10003291', 2, 1.0, 19.0, -1.0)
(47, datetime.datetime(2023, 2, 3, 0, 0), 'Second Class', 'Consumer', 'United States', 'Westland', 'Michigan', 48185, 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10001713', 4, 8.4, 201.6, 21.599999999999994)
(48, datetime.datetime(2022, 2, 16, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Dover', 'Delaware', 19901, 'East', 'Technology', 'Accessories', 'TEC-AC-10002167', 3, 2.5, 47.5, -2.5)
(49, datetime.datetime(2022, 5, 6, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Dover', 'Delaware', 19901, 'East', 'Technology', 'Phones', 'TEC-PH-10003988', 2, 0.8, 19.2, -0.8000000000000007)
(50, datetime.datetime(2023, 6, 18, 0, 0), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', 47150, 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10004410', 6, 1.6, 38.4, 8.399999999999999)
(51, datetime.datetime(2022, 1, 11, 0, 0), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', 47150, 'Central', 'Office Supplies', 'Labels', 'OFF-LA-10002762', 6, 3.2, 76.8, 6.799999999999997)
(52, datetime.datetime(2023, 9, 9, 0, 0), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', 47150, 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10001706', 2, 0.4, 9.6, -0.40000000000000036)
(53, datetime.datetime(2022, 1, 31, 0, 0), 'Standard Class', 'Consumer', 'United States', 'New Albany', 'Indiana', 47150, 'Central', 'Furniture', 'Chairs', 'FUR-CH-10003061', 1, 4.5, 85.5, 15.5)
(54, datetime.datetime(2023, 7, 30, 0, 0), 'Standard Class', 'Corporate', 'United States', 'New York City', 'New York', 10024, 'East', 'Office Supplies', 'Fasteners', 'OFF-FA-10000304', 7, 0.6, 19.4, -0.6000000000000014)
(55, datetime.datetime(2023, 10, 17, 0, 0), 'Standard Class', 'Corporate', 'United States', 'New York City', 'New York', 10024, 'East', 'Technology', 'Phones', 'TEC-PH-10002447', 5, 41.2, 988.8, 138.79999999999995)
(56, datetime.datetime(2023, 7, 6, 0, 0), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', 12180, 'East', 'Office Supplies', 'Storage', 'OFF-ST-10000604', 6, 10.5, 199.5, -0.5)
(57, datetime.datetime(2023, 9, 15, 0, 0), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', 12180, 'East', 'Office Supplies', 'Paper', 'OFF-PA-10001569', 5, 1.5, 28.5, -1.5)
(58, datetime.datetime(2022, 8, 9, 0, 0), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', 12180, 'East', 'Furniture', 'Chairs', 'FUR-CH-10003968', 5, 6.4, 313.6, 23.600000000000023)
(59, datetime.datetime(2022, 4, 5, 0, 0), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', 12180, 'East', 'Office Supplies', 'Paper', 'OFF-PA-10000587', 2, 0.4, 9.6, -0.40000000000000036)
(60, datetime.datetime(2023, 6, 24, 0, 0), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', 12180, 'East', 'Technology', 'Accessories', 'TEC-AC-10002167', 2, 1.5, 28.5, 8.5)
(61, datetime.datetime(2022, 3, 10, 0, 0), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', 12180, 'East', 'Office Supplies', 'Binders', 'OFF-BI-10001460', 4, 1.0, 49.0, 9.0)
(62, datetime.datetime(2023, 4, 8, 0, 0), 'First Class', 'Consumer', 'United States', 'Troy', 'New York', 12180, 'East', 'Office Supplies', 'Art', 'OFF-AR-10001868', 1, 0.0, 0.0, 0.0)
(63, datetime.datetime(2023, 10, 16, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90004, 'West', 'Technology', 'Accessories', 'TEC-AC-10004633', 2, 0.3, 9.7, -0.3000000000000007)
(64, datetime.datetime(2023, 8, 2, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90004, 'West', 'Office Supplies', 'Binders', 'OFF-BI-10001078', 6, 0.6, 29.4, 9.399999999999999)
(65, datetime.datetime(2022, 11, 5, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90004, 'West', 'Office Supplies', 'Paper', 'OFF-PA-10003892', 3, 7.5, 142.5, 12.5)
(66, datetime.datetime(2022, 5, 6, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', 90004, 'West', 'Furniture', 'Furnishings', 'FUR-FU-10000397', 4, 1.6, 78.4, 8.400000000000006)
(67, datetime.datetime(2022, 3, 26, 0, 0), 'Standard Class', 'Home Office', 'United States', 'Chicago', 'Illinois', 60610, 'Central', 'Furniture', 'Chairs', 'FUR-CH-10001146', 5, 10.5, 199.5, 19.5)
(68, datetime.datetime(2022, 4, 10, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Gilbert', 'Arizona', 85234, 'West', 'Office Supplies', 'Art', 'OFF-AR-10002671', 8, 33.3, 1076.7, 136.70000000000005)
(69, datetime.datetime(2022, 8, 12, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Gilbert', 'Arizona', 85234, 'West', 'Technology', 'Phones', 'TEC-PH-10002726', 4, 5.1, 164.9, 4.900000000000006)
(70, datetime.datetime(2022, 2, 25, 0, 0), 'First Class', 'Consumer', 'United States', 'Springfield', 'Virginia', 22153, 'South', 'Office Supplies', 'Paper', 'OFF-PA-10000482', 2, 1.6, 78.4, 8.400000000000006)
(71, datetime.datetime(2022, 11, 29, 0, 0), 'Standard Class', 'Consumer', 'United States', 'New York City', 'New York', 10009, 'East', 'Office Supplies', 'Binders', 'OFF-BI-10004654', 1, 0.0, 0.0, 0.0)
(72, datetime.datetime(2022, 12, 18, 0, 0), 'Second Class', 'Consumer', 'United States', 'Jackson', 'Michigan', 49201, 'Central', 'Office Supplies', 'Paper', 'OFF-PA-10004675', 3, 0.6, 19.4, -0.6000000000000014)
(73, datetime.datetime(2023, 3, 7, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Memphis', 'Tennessee', 38109, 'South', 'Furniture', 'Chairs', 'FUR-CH-10000513', 8, 16.6, 813.4, 23.399999999999977)
(74, datetime.datetime(2023, 7, 12, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Memphis', 'Tennessee', 38109, 'South', 'Furniture', 'Furnishings', 'FUR-FU-10003708', 2, 3.0, 97.0, 7.0)
(75, datetime.datetime(2022, 10, 21, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Memphis', 'Tennessee', 38109, 'South', 'Office Supplies', 'Storage', 'OFF-ST-10004123', 1, 1.4, 68.6, 8.599999999999994)
(76, datetime.datetime(2023, 4, 17, 0, 0), 'First Class', 'Corporate', 'United States', 'Houston', 'Texas', 77041, 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10004182', 3, 0.0, 0.0, 0.0)
(77, datetime.datetime(2023, 5, 20, 0, 0), 'First Class', 'Corporate', 'United States', 'Houston', 'Texas', 77041, 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10000260', 3, 0.4, 9.6, -0.40000000000000036)
(78, datetime.datetime(2023, 5, 13, 0, 0), 'First Class', 'Corporate', 'United States', 'Houston', 'Texas', 77041, 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10000615', 3, 0.6, 29.4, 9.399999999999999)
(79, datetime.datetime(2022, 10, 20, 0, 0), 'Second Class', 'Consumer', 'United States', 'Houston', 'Texas', 77070, 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10003194', 5, 0.4, 19.6, -0.3999999999999986)
(80, datetime.datetime(2023, 10, 22, 0, 0), 'First Class', 'Corporate', 'United States', 'Decatur', 'Alabama', 35601, 'South', 'Office Supplies', 'Appliances', 'OFF-AP-10002118', 1, 6.3, 203.7, 13.699999999999989)
(81, datetime.datetime(2022, 7, 20, 0, 0), 'First Class', 'Corporate', 'United States', 'Decatur', 'Alabama', 35601, 'South', 'Office Supplies', 'Binders', 'OFF-BI-10002309', 3, 0.4, 19.6, -0.3999999999999986)
(82, datetime.datetime(2022, 11, 16, 0, 0), 'Standard Class', 'Consumer', 'United States', 'San Francisco', 'California', 94122, 'West', 'Office Supplies', 'Art', 'OFF-AR-10002053', 5, 0.5, 9.5, -0.5)
(83, datetime.datetime(2022, 11, 10, 0, 0), 'Standard Class', 'Consumer', 'United States', 'San Francisco', 'California', 94122, 'West', 'Office Supplies', 'Storage', 'OFF-ST-10002370', 1, 0.8, 19.2, -0.8000000000000007)
(84, datetime.datetime(2022, 3, 15, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Durham', 'North Carolina', 27707, 'South', 'Office Supplies', 'Envelopes', 'OFF-EN-10000927', 7, 6.0, 194.0, 14.0)
(85, datetime.datetime(2023, 10, 3, 0, 0), 'First Class', 'Home Office', 'United States', 'Chicago', 'Illinois', 60623, 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10003656', 3, 4.6, 225.4, 15.400000000000006)
(86, datetime.datetime(2022, 3, 20, 0, 0), 'Second Class', 'Consumer', 'United States', 'Columbia', 'South Carolina', 29203, 'South', 'Furniture', 'Chairs', 'FUR-CH-10000863', 2, 15.0, 285.0, 25.0)
(87, datetime.datetime(2023, 12, 4, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Rochester', 'Minnesota', 55901, 'Central', 'Technology', 'Accessories', 'TEC-AC-10001998', 1, 1.0, 19.0, -1.0)
(88, datetime.datetime(2023, 11, 24, 0, 0), 'Standard Class', 'Consumer', 'United States', 'Rochester', 'Minnesota', 55901, 'Central', 'Office Supplies', 'Labels', 'OFF-LA-10000134', 2, 0.5, 9.5, -0.5)
(89, datetime.datetime(2023, 12, 30, 0, 0), 'Second Class', 'Home Office', 'United States', 'Houston', 'Texas', 77095, 'Central', 'Office Supplies', 'Storage', 'OFF-ST-10003442', 7, 8.0, 152.0, 12.0)
(90, datetime.datetime(2022, 5, 23, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Los Angeles', 'California', 90036, 'West', 'Office Supplies', 'Art', 'OFF-AR-10004930', 3, 0.4, 19.6, -0.3999999999999986)
(91, datetime.datetime(2023, 4, 6, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Los Angeles', 'California', 90036, 'West', 'Technology', 'Phones', 'TEC-PH-10004093', 2, 1.4, 68.6, 8.599999999999994)
(92, datetime.datetime(2022, 3, 23, 0, 0), 'Standard Class', 'Corporate', 'United States', 'Los Angeles', 'California', 90036, 'West', 'Office Supplies', 'Paper', 'OFF-PA-10000304', 1, 0.2, 9.8, -0.1999999999999993)
(93, datetime.datetime(2023, 4, 7, 0, 0), 'Second Class', 'Consumer', 'United States', 'Minneapolis', 'Minnesota', 55407, 'Central', 'Office Supplies', 'Paper', 'OFF-PA-10003177', 2, 0.2, 9.8, -0.1999999999999993)
(94, datetime.datetime(2022, 5, 13, 0, 0), 'Second Class', 'Consumer', 'United States', 'Minneapolis', 'Minnesota', 55407, 'Central', 'Furniture', 'Furnishings', 'FUR-FU-10003799', 3, 2.5, 47.5, -2.5)
(95, datetime.datetime(2022, 4, 23, 0, 0), 'Second Class', 'Consumer', 'United States', 'Minneapolis', 'Minnesota', 55407, 'Central', 'Office Supplies', 'Binders', 'OFF-BI-10002852', 2, 0.9, 29.1, 9.100000000000001)